### ISSUE TITLE
Use ROCK in Tempo

### ISSUE THREAD

**Issue by mmkay** [canonical/tempo-k8s-operator#107]
### Enhancement Proposal

We recently created a new Tempo ROCK: https://github.com/canonical/tempo-rock

We should use the rock in tempo charm instead of the current image.

**Comment by PietroPasotti** [comment]
we are pivoting towards tempo distributed aka tempo-coordinator-k8s + tempo-worker-k8s and the worker charm already is using a rock. Obsoleting this task.
