### ISSUE TITLE
Add more identifying information to the trace query result table

### ISSUE THREAD

**Issue by shayancanonical** [canonical/tempo-k8s-operator#111]
### Enhancement Proposal

Currently, the following is the layout of the trace query result table:
![image](https://github.com/canonical/tempo-k8s-operator/assets/99665202/e38e5070-12f4-47b7-a9eb-0712a345b44e)

The proposal is to add more identifying information to this table so that the user has enough context to pick the trace that they are interested in. Off the top of my head, the following information may be useful:
1. The unit of the trace (which will inherently imply the application of the trace)
2. The hook of the trace (e.g. `update-status` or `a-relation-created`)

Additionally, providing filtering mechanisms may be very useful. For instance, if we want to see what happened during relation formation, we can query `a-relation-created` event traces and just look at traces for this hook (across various units and applications)

**Comment by PietroPasotti** [comment]
could definitely do:
`catalogue/0 update-status charm exec
