### ISSUE TITLE
scaling-monolithic deployment mode

### ISSUE THREAD

**Issue by PietroPasotti** [canonical/tempo-k8s-operator#119]
### Enhancement Proposal

It seems that with the 'all' target, you cannot scale tempo up. 
Scaling to multiple units requires the 'scaling-monolithic' mode, which also means tempo requires the s3 integration.

https://grafana.com/docs/tempo/latest/setup/deployment/#scaling-monolithic-mode

proposal:
add a `scaling:bool` config option to tempo. If True, set the target to scaling-monolithic and set blocked until we have an s3 integration.

**Comment by PietroPasotti** [comment]
counterproposal: 

tempo-k8s can detect if it's scaled and if it has s3 configured.

if scaled and s3 configured: run all units with `scaling-monolithic` mode.
If scaled and s3 not ready: run leader with `all`, all other units go to blocked and alert of the missing s3 relation.

**Comment by mmkay** [comment]
Completed in #127.
