### ISSUE TITLE
charm_tracing charmlib does not correctly wrap staticmethods in instrumented code

### ISSUE THREAD

**Issue by shayancanonical** [canonical/tempo-k8s-operator#120]
### Bug Description

The charm_tracing charm lib [has a fixme comment](https://github.com/canonical/tempo-k8s-operator/blob/main/lib/charms/tempo_k8s/v1/charm_tracing.py#L543-L546) which manifested and was observed in mysql-router-k8s-operator's unit tests (see logs below for error trace).

### To Reproduce

1. git clone git@github.com:canonical/mysql-router-k8s-operator.git
2. git checkout feature/tempo_tracing
3. virtualenv venv
4. source venv/bin/activate
5. pip install poetry tox
6. tox -e unit

### Environment

tempo_k8s charm_tracing lib: v1.6

### Relevant log output

```shell
tests/unit/test_workload.py:188: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _  

args = ('# File automatically generated during MySQL Router bootstrap\n[DEFAULT]\nname=system\nkeyring_path=/var/lib/mysqlrou...e\n\n[rest_routing]\nrequire_realm=default_auth_realm\n\n[rest_metadata_cache]\nrequire_realm=default_auth_realm\n\n',)                
kwargs = {}, name = 'AuthenticatedWorkload._parse_username_from_config'                                  

    @functools.wraps(callable)
    def wrapped_function(*args, **kwargs):  # type: ignore                                               
        name = getattr(callable, "__qualname__", getattr(callable, "__name__", str(callable)))           
        with _span(f"{'(static) ' if static else ''}{qualifier} call: {name}"):  # type: ignore          
            if static:                              
                # fixme: do we or don't we need [1:]?                                                    
                #  The _trace_callable decorator doesn't always play nice with @staticmethods.           
                #  Sometimes it will receive 'self', sometimes it won't.                                 
                # return callable(*args, **kwargs)  # type: ignore                                       
>               return callable(*args[1:], **kwargs)  # type: ignore                                     
E               TypeError: AuthenticatedWorkload._parse_username_from_config() missing 1 required positional argument: 'config_file_text'
```

### Additional context

static method signature:

```
@staticmethod
def _parse_username_from_config(config_file_text: str) -> str:
```

**Comment by PietroPasotti** [comment]
Yeah that one has been bugging me for ages, never managed to figure out what's going on.
Will see if I can write a consistent reproducer for both failure modes, thanks for the reference

**Comment by PietroPasotti** [comment]
Huh, found out what the issue is.
![image](https://github.com/canonical/tempo-k8s-operator/assets/6230162/6933a16e-ba71-4b06-9650-c61ffe584b2f)

Calling a static method on an instance passes, calling it on the type, fails.
Working on a fix...
