### ISSUE TITLE
tempo should probably present itself via its ingressed url

### ISSUE THREAD

**Issue by PietroPasotti** [canonical/tempo-k8s-operator#29]
### Bug Description

right now traefik advertises its fqdn in the `tracing` relation databag.
Cross-model providers will therefore not be able to send traces to it.

If we have an ingress, we should probably advertise our ingress address instead.

### To Reproduce

-

### Environment

-

### Relevant log output

```shell
-
```

**Comment by mmkay** [comment]
Fixed by #98 .
