### ISSUE TITLE
Tempo libraries are out of sync with Charmhub

### ISSUE THREAD

**Issue by lucabello** [canonical/tempo-k8s-operator#54]
### Bug Description

The libraries shouldn't have local changes, since the version numbers on Charmhub match the one main. We probably forgot to bump the `LIBPATCH` version (and ignored the CI warning about it, I guess), so the libraries won't be able to be published by CI.

Bumping the `LIBPATCH` version on both libraries should be enough to fix the issue.

### To Reproduce

```bash
$ charmcraft fetch-lib
...
Library charms.tempo_k8s.v0.charm_tracing has local changes, cannot be updated.
Library charms.tempo_k8s.v1.tracing has local changes, cannot be updated.
...
```

### Environment

-

### Relevant log output

```shell
-
```

**Comment by mmkay** [comment]
Looks like new versions are already published correctly after the new pull requests so we can close this one :)
