### ISSUE TITLE
Remove need to specify tracing endpoint in charm code

### ISSUE THREAD

**Issue by mmkay** [canonical/tempo-k8s-operator#56]
### Enhancement Proposal

Currently, charms using `@trace_charm` from `charm_tracing.py` need to specify a method pointing at the ingester URL:

```python
@trace_charm(tracing_endpoint="tempo_otlp_grpc_endpoint", service_name=TRACING_APP_NAME)
class TempoTesterCharm(CharmBase):

(...)

    def tempo_otlp_grpc_endpoint(self) -> Optional[str]:
        """Endpoint at which the charm tracing information will be forwarded."""
        if self.tracing.is_ready():
            return self.tracing.otlp_grpc_endpoint()
        else:
            return None
```

At the same time, `trace_charm` is always using OTLP/GRPC (changing for OTLP/HTTP in #53 ) so this method always returns `self.tracing.otlp_(...)_endpoint()`. We could pass `tracing` to the annotation instead:

```python
@trace_charm(tracing_relation_wrapper="tracing", protocol="otlp_http", service_name = ...)
class MyCharm:
    def __init__:
        self.tracing = TracingRequirer | TracingProvider(...)
```

and then use the protocol argument to get what we need out of `getattr(charm, tracing_relation_wrapper)`. 

We'll need to consider how to pass SSL enablement to the endpoint. Most likely we could check when the method used to get the cert returns non-null.

**Comment by PietroPasotti** [comment]
I think a better solution, that keeps the decorator agnostic as to what is providing the endpoint, is being proposed already in #136 + #135
