### ISSUE TITLE
Tracer contextvar is sometimes empty

### ISSUE THREAD

**Issue by PietroPasotti** [canonical/tempo-k8s-operator#60]
After the switch to the new dependency [otlp_http] it seems there's been a change in the way `tracer` behaves in the context here. I started getting scenario test failures on `test_base_tracer_endpoint_event` so I started debugging and noticed that `_get_tracer()` returns None in the context of the span in the function instrumented by `@trace`. After going through the context I noticed that there is a `tracer` in the context but with a different reference, so I added this fallback retrieval.

To test it doesn't only happen on my local environment I've tried removing the fallback on a test draft PR and it looks the same behavior happens there: https://github.com/canonical/tempo-k8s-operator/actions/runs/7412918066/job/20170743398?pr=58

Branch diff: https://github.com/canonical/tempo-k8s-operator/compare/switch-to-otlp-http...temp/otlp-http-without-get-context

As fallback is triggered only in case `tracer.get()` doesn't find anything I felt it's okay to add it here in that way. I must admit though that it's dealing with a symptom, not addressing the cause I couldn't really pinpoint.

Do you think we should open a bug to investigate that further?

_Originally posted by @mmkay in https://github.com/canonical/tempo-k8s-operator/pull/55#discussion_r1442127616_

**Comment by PietroPasotti** [comment]
Additional thought: the pydantic warnings might be related. That's another dep we bumped.

**Comment by mmkay** [comment]
There might be more uncaught yet cases with no tracer, from @Abuelodelanada in mimir-coordinator:

```
unit-coord-0: 18:33:14.001 WARNING unit.coord/0.juju-log certificates:183: Couldn't find context var for tracer: span will be skipped
unit-coord-0: 18:33:14.011 WARNING unit.coord/0.juju-log certificates:183: Couldn't find context var for tracer: span will be skipped
unit-coord-0: 18:33:14.016 WARNING unit.coord/0.juju-log certificates:183: Couldn't find context var for tracer: span will be skipped
unit-coord-0: 18:33:14.021 WARNING unit.coord/0.juju-log certificates:183: Couldn't find context var for tracer: span will be skipped
```

**Comment by PietroPasotti** [comment]
so I think this is the result of some python weirdness.
in the test file that's triggering errors, we're doing:
```python
from charms.tempo_k8s.v1.charm_tracing import _autoinstrument as autoinstrument
from lib.charms.tempo_k8s.v1.charm_tracing import get_current_span, trace
@trace 
def foo...

autoinstrument(CharmType)
```

as a result, we're in fact creating two python Module objects with two different `tracer` context vars.

Some debug logs and breakpoint inspection show that there are two different memory addresses assigned to what's supposed to be 'the same' context var:

![image](https://github.com/user-attachments/assets/6f092662-f485-402f-8409-9628814d193c)

**Comment by PietroPasotti** [comment]
Adjusting the imports to:
```python
from charms.tempo_k8s.v1.charm_tracing import (
    autoinstrument, get_current_span, trace
)
```

fixes the issue.
What's left to be determined is whether there's anything we can/should do to help prevent users from doing the same mistake

**Comment by PietroPasotti** [comment]
**Option 1:**
- leave the fallback behaviour in, and add a warning to let the user know they're doing something wrong.

**Option 2:**
- remove the fallback, let the user figure out that they're doing something wrong by themselves

**Option 3:**
- adapt the fallback code to raise an exception in case we couldn't find the tracer in the local context but we could find it in the copied context (which indicates a double import path problem). This will force the user to correct the mistake. 

In general it's still unclear to me whether a double import path is in fact a legitimate use case in some situation or always an error.
If there's a legitimate use case, we should add a mechanism for disabling the 'warning/exception' in options 1 and 3 respectively if the user knows what they're doing.
