### ISSUE TITLE
use pebble notices to get rid of that 'tempo is still starting' message on active

### ISSUE THREAD

**Issue by PietroPasotti** [canonical/tempo-k8s-operator#78]
### Enhancement Proposal

right now, tempo takes a bit longer to start than it takes to go through the startup phase.
consequently after deploy the charm goes to active but instructs the user to wait for update-status to have the charm check again whether the tempo service readiness check returns true.

We should use pebble notices to have the charm fix itself as soon as the service comes up.

**Comment by mmkay** [comment]
Fixed by #81.
